
#ifndef STRING_VALUES_H
#define STRING_VALUES_H

#define PHRASE "CATCH THE PHRASE!"
#define TITLE_PLAYER1 "Catch the Phrase -- Player 1"
#define TITLE_PLAYER2 "Catch the Phrase -- Player 2"
#define SETTING_UP "Setting up..."
#define CREATING_SOCKET "Creating socket..."
#define CREATING_SOCKET_ADDRESS "Creating socket address..."
#define BINDING_SOCKET "Binding socket..."
#define LISTENING_SOCKET "Listening to port..."
#define FINDING_HOST "Finding host..."
#define CONNECTING_TO_SERVER "Connecting to server..."
#define CONNECTED_TO_SERVER "Connected to server."
#define WAITING_FOR_PLAYER "Waiting for player..."
#define PLAYER_CONNECTED "Player connected."
#define WAITING_FOR_TOPIC "Waiting for topic..."
#define PRESS_ENTER "Press enter to continue..."
#define YOUR_TURN "YOUR TURN"
#define OPPONENT_TURN "OPPONENT'S TURN"

#define SOCKET_ERROR "Error: socket() Failed."
#define BIND_ERROR "Error: bind() Failed."
#define MALLOC_ERROR "Error: malloc() Failed."
#define ACCEPT_ERROR "Error: accept() Failed."
#define CONNECT_ERROR "Error: connect() Failed."
#define HOST_ERROR "Error: no such host."
#define WON "Player "
#define EXITING "Exiting... Press ESC key to close window."

// SYSTEM MESSAGES
#define DISPLAY_TOPIC "System Message> The chosen topic is: "
#define WAITING_FOR_PHRASE "System Message> Waiting for opponent to set a phrase..."
#define ALREADY_GUESSED "System Message> You already guessed that letter."
#define GUESS_PHRASE "System Message> Guess a letter: "
#define SET_PHRASE "System Message> Set a phrase. "
#define DISPLAY_PHRASE "System Message> Your phrase is: "
#define NOT_IN_PHRASE "System Message> Letter not in Phrase."
#define PLAYER_WON "System Message> You guessed the Phrase!"
#define OPPONENT_WON "System Message> Your opponent guessed the Phrase!"
#define OPPONENTS_TURN "System Message> Waiting for opponent to guess a letter..."
#define OPPONENT_NOT_IN_PHRASE "System Message> Your opponent guessed a letter not in the phrase."
#define PRINT_LETTER "System message> You guessed the letter "
#define PRINT_LETTER_OPPONENT "System message> Your opponent guessed the letter "
#define GUESS_MARKED_SPOT "System message> You guessed a marked spot!"
#define GUESS_MARKED_SPOT_OPPONENT "System message> Your opponent guessed a marked spot!"
#define THREE_IN_A_ROW "System message> You guessed three letters in a row!"
#define THREE_IN_A_ROW_OPPONENT "System message> Your opponent guessed three letters in a row!"
#define REVEAL_A_LETTER "System message> A letter has been revealed: "
#define REVEAL_A_LETTER_OPPONENT "System message> Your opponent had a letter revealed: "
#define REVEAL_NOT_PRESENT_LETTER "System message> A letter not in the phrase has been revealed: "
#define REVEAL_NOT_PRESENT_LETTER_OPPONENT "System message> Your opponent had a letter revealed not in the phrase: "
#define POWER_UP_TRIGGERED "System message> You triggered a power up!"
#endif